[package]
name = "rust-c-ffi-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# Declare this type of crate type is "cdylib"
crate-type = ["cdylib"]

[dependencies]
